apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-

images:
- name: yellowsunn/simpleforum-notification-consumer
  newTag: SNAPSHOT-20230612162436
resources:
- ../../base
